### PR TITLE
[photon-client] ATFL Settings card unit and styling fixes

### LINKED ISSUE #966: Apriltag Layout reports incorrect units
Units for the Apriltag Layout in the settings tab are wrong.

image

### PR DESCRIPTION
**Pull request by srimanachanta**
closes #966

### CODE REVIEW

File: photon-client/src/components/settings/ApriltagControlCard.vue [hunk 1]
```diff
@@ -3,18 +3,21 @@ import { useSettingsStore } from "@/stores/settings/GeneralSettingsStore";
...
+    z: euler.z * (180.0 / Math.PI)
+  };
+};
 </script>
 
 <template>
-  <v-card dark class="mb-3 pr-6 pb-3" style="background-color: #006492">
-    <v-card-title>Apriltag Layout</v-card-title>
+  <v-card dark class="pr-6 pb-3" style="background-color: #006492">
+    <v-card-title>Apriltag Field Layout</v-card-title>
```
Comment (shueja-personal) [inline photon-client/src/components/settings/ApriltagControlCard.vue:20]: Please capitalize as AprilTag, while we're changing this text.

**Review by shueja-personal — CHANGES_REQUESTED** [review]

**Review by shueja-personal — APPROVED** [review]
