### PR TITLE
Fix Arducam OV9782 Exposure Changing After Reboot

### LINKED ISSUE #2353: Arducam OV9782 Exposure Changes After Reboot
**Describe the bug**
The Arducam OV9782 has the exact same auto exposure problems as the OV9281 as described in #1771.  
**To Reproduce**
1. Set an exposure value for an Arducam OV9782 
2. Power cycle the coprocessor
3. Observe that the exposure is not the same as it was before the power cycle
4. Toggling auto exposure on and off resets the exposure to the value before power cycling

**Platform:**
 - Hardware Platform: Orange Pi 5
   - How is it powered? Buck boost
 - Network Configuration: plugged into robot radio 
 - PhotonVision Version: 2026.2.1
 - Camera(s) Used: Arducam OV9782

**Additional context**
This issue could probably be solved by checking for the OV9782 quirk and applying the solution in #1814.

### PR DESCRIPTION
**Pull request by Watermilan412**
The Arducam OV9782's exposure value is changed after a power cycle just like the OV9281. Toggling auto exposure on and off fixes it.

## Description

Adds a check for the OV9782 quirk and uses the same auto exposure toggle that fixed the OV9281's problems.

Closes #2353 

Merge checklist:
- [x] Pull Request title is [short, imperative summary](https://cbea.ms/git-commit/) of proposed changes
- [x] The description documents the _what_ and _why_, including events that led to this PR
- [ ] If this PR changes behavior or adds a feature, user documentation is updated
- [ ] If this PR touches photon-serde, all messages have been regenerated and hashes have not changed unexpectedly
- [ ] If this PR touches configuration, this is backwards compatible with all settings going back to the previous seasons's last release (seasons end after champs ends)
- [ ] If this PR touches pipeline settings or anything related to data exchange, the frontend typing is updated
- [ ] If this PR addresses a bug, a regression test for it is added

### CODE REVIEW

File: photon-core/src/main/java/org/photonvision/vision/camera/USBCameras/GenericUSBCameraSettables.java [hunk 1]
```diff
@@ -170,17 +170,18 @@ public void setAutoWhiteBalance(boolean autoWB) {
     @Override
     public void setAutoExposure(boolean cameraAutoExposure) {
         if (configuration.cameraQuirks.hasQuirk(CameraQuirk.ArduOV9281Controls)
-                && !cameraAutoExposure) {
-            // OV9281 on Linux seems to sometimes ignore our exposure requests on first boot if we're in
-            // manual mode. Poking the camera into and out of auto exposure seems to fix it.
+                || configuration.cameraQuirks.hasQuirk(CameraQuirk.ArduOV9782Controls)
+                        && !cameraAutoExposure) {
```
Comment (mcm001) [inline photon-core/src/main/java/org/photonvision/vision/camera/USBCameras/GenericUSBCameraSettables.java]: I'd double check your order of operations here?

**Comment by mcm001** [comment]
@roberttuttle are you able to give this PR a try?

**Comment by Watermilan412** [comment]
@mcm001 I tested this on an Orange Pi 5 running 2 Arducam OV9782s and confirmed that this fixes the exposure problems.

**Comment by roberttuttle** [comment]
> @roberttuttle are you able to give this PR a try?

Confirmed fix as well at last night's team meeting. Thanks!

**Review by mcm001 — APPROVED** [review]
Thanks yall!

**Comment by seanhandel** [comment]
We (FRC team 8793) noticed this same problem this weekend at the Central Valley District event. It occurred randomly throughout the matches over the weekend. The driver did learn to toggle the switch before each match but that is pretty risky given how stressful the pre-match setup is. Is this fix incorporated into the latest version or how could we apply it to our setup? Thanks for fixing it!

**Comment by samfreund** [comment]
> We (FRC team 8793) noticed this same problem this weekend at the Central Valley District event. It occurred randomly throughout the matches over the weekend. The driver did learn to toggle the switch before each match but that is pretty risky given how stressful the pre-match setup is. Is this fix incorporated into the latest version or how could we apply it to our setup? Thanks for fixing it!

Which camera are you guys using? This fix is in 2026.2.2, although I'd recommend using latest, which is 2026.3.2 at this time.

**Comment by seanhandel** [comment]
We're using four Arducam OV9281's for AprilTag detection. We'll try using the latest PV version to see if that fixes it. We have two weeks before Districts so now is a good time to mess with it. Thanks!

**Comment by samfreund** [comment]
> We're using four Arducam OV9281's for AprilTag detection. We'll try using the latest PV version to see if that fixes it. We have two weeks before Districts so now is a good time to mess with it. Thanks!

What version were you on that you guys saw this issue?

**Comment by seanhandel** [comment]
2026.2.2

**Comment by samfreund** [comment]
> 2026.2.2

I would expect it to be working on that version. It might be a separate issue, or our fix isn't fully robust for all cases. Could you provide some more detail about your setup and logs?

**Comment by seanhandel** [comment]
Our setup is two Orange Pi 5's with two Arducam OV9281's connected to each.
We're running PV v2026.2.2 on both. I'll have to grab the logs later today
- what do you need for me to provide from the logs?

**Comment by mcm001** [comment]
I would like to try to reproduce this myself locally. If we can make it happen with just V4L, it may be worth digging deeper into the USB UVC packets themselves or the kernel. Or just writing an email to adducam

**Comment by seanhandel** [comment]
We're going to update to the latest version of PV tonight and will post back here if we still see the autoexposure bug after upgrade.
