### PR TITLE
Fixes #1053

### LINKED ISSUE #1053: Updating from 2023 json to SQL file throws error on deserializing April Tag pipeline
In #981, the enum `TargetModel.k6in_16h5` was renamed to `kAprilTag6in_16h5`. When trying to update the settings stored in the JSON files, this causes the deserialization of the pipeline to fail and the pipeline reverts to reflective. 

** Exception **
```
[2023-12-17 11:17:33] [General - LegacyConfigProvider] [ERROR] Exception while deserializing cameras/Arducam_OV9281_USB_Camera/pipelines/New Pipeline.json: Cannot deserialize value of type `org.photonvision.vision.target.TargetModel` from String "k6in_16h5": not one of the values accepted for Enum class: [k2016HighGoal, kAprilTag6in_16h5, kAprilTag6p5in_36h11, k2019DualTarget, k2020HighGoalOuter, k2022CircularCargoBall, kCircularPowerCell7in]
 at [Source: (File); line: 66, column: 19] (through reference chain: org.photonvision.vision.pipeline.AprilTagPipelineSettings["targetModel"])
[2023-12-17 11:17:33] [General - LegacyConfigProvider] [ERROR] com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `org.photonvision.vision.target.TargetModel` from String "k6in_16h5": not one of the values accepted for Enum class: [k2016HighGoal, kAprilTag6in_16h5, kAprilTag6p5in_36h11, k2019DualTarget, k2020HighGoalOuter, k2022CircularCargoBall, kCircularPowerCell7in]
 at [Source: (File); line: 66, column: 19] (through reference chain: org.photonvision.vision.pipeline.AprilTagPipelineSettings["targetModel"])
        at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
        at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:2002)
        at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:1230)
        at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:415)
        at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._fromString(EnumDeserializer.java:279)
        at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:248)
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
        at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._deserialize(AsArrayTypeDeserializer.java:120)
        at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer.deserializeTypedFromObject(AsArrayTypeDeserializer.java:61)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1296)
        at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3637)
        at org.photonvision.common.util.file.JacksonUtils.deserialize(JacksonUtils.java:88)
        at org.photonvision.common.configuration.LegacyConfigProvider.lambda$loadCameraConfigs$2(LegacyConfigProvider.java:339)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.photonvision.common.configuration.LegacyConfigProvider.loadCameraConfigs(LegacyConfigProvider.java:351)
        at org.photonvision.common.configuration.LegacyConfigProvider.load(LegacyConfigProvider.java:213)
        at org.photonvision.common.configuration.ConfigManager.translateLegacyIfPresent(ConfigManager.java:96)
        at org.photonvision.common.configuration.ConfigManager.load(ConfigManager.java:183)
        at org.photonvision.Main.main(Main.java:348)
```

### PR DESCRIPTION
**Pull request by crschardt**
Added `@JsonAlias` to link the older tag names to the current ones in the TargetModel enum.

### CODE REVIEW

**Comment by mcm001** [comment]
Can we add a unit test to prove this works? Ideally one that fails with the old code but passes now

**Comment by crschardt** [comment]
I've added a test that seems to work for this PR. It passed on the current PR and will fail if I remove the `@JsonAlias` line. I tried to add a test to confirm that it was returning the right value, but proved to be beyond my understanding of Java.

File: photon-core/src/test/java/org/photonvision/common/configuration/ConfigTest.java [hunk 1]
```diff
@@ -141,4 +142,18 @@ public void testJacksonHandlesOldVersions() throws IOException {
...
+    @Test
+    public void testJacksonHandlesOldTargetEnum() throws IOException {
+        var str =
+                "[ \"AprilTagPipelineSettings\", {\n" + "  \"targetModel\" : \"k6in_16h5\"\n" + "} ]\n";
+        var writer = new FileWriter("test.json");
+        writer.write(str);
+        writer.flush();
+        writer.close();
+        Assertions.assertDoesNotThrow(
+                () -> JacksonUtils.deserialize(Path.of("test.json"), CVPipelineSettings.class));
```
Comment (mcm001) [inline photon-core/src/test/java/org/photonvision/common/configuration/ConfigTest.java:155]: What I would do here is cast the result to an ApriltagPipelienSettings so you can check it got loaded right

File: photon-core/src/test/java/org/photonvision/common/configuration/ConfigTest.java [hunk 2]
```diff
@@ -141,4 +142,18 @@ public void testJacksonHandlesOldVersions() throws IOException {
 
         new File("test.json").delete();
     }
+
+    @Test
+    public void testJacksonHandlesOldTargetEnum() throws IOException {
+        var str =
+                "[ \"AprilTagPipelineSettings\", {\n" + "  \"targetModel\" : \"k6in_16h5\"\n" + "} ]\n";
+        var writer = new FileWriter("test.json");
```
Comment (mcm001) [inline photon-core/src/test/java/org/photonvision/common/configuration/ConfigTest.java:150]: Can you change this to Files.makeTempFile or something?

Comment (crschardt) [reply photon-core/src/test/java/org/photonvision/common/configuration/ConfigTest.java:150]: There is another test in this file that I copied and this is how they did it. I'll make the change.

File: photon-core/src/test/java/org/photonvision/common/configuration/ConfigTest.java (hunk 1 above)
Comment (crschardt) [reply photon-core/src/test/java/org/photonvision/common/configuration/ConfigTest.java:155]: Can I add another assertion inside the lambda?

Comment (crschardt) [reply photon-core/src/test/java/org/photonvision/common/configuration/ConfigTest.java]: Since throwing an exception will cause the test to fail. I removed the `assertDoesNotThrow` and added an `assertEquals` on the deserialized value of targetModel.

File: photon-core/src/test/java/org/photonvision/common/configuration/ConfigTest.java (hunk 2 above)
Comment (crschardt) [reply photon-core/src/test/java/org/photonvision/common/configuration/ConfigTest.java]: This function, and the one before it now use temp files.

**Review by mcm001 — APPROVED** [review]
