### PR TITLE
Draw 2D contours on top (Fixes issue #102)

### LINKED ISSUE #102: Target number is overdrawn by 3d model
image

### PR DESCRIPTION
**Pull request by MarkGhebrial**
Closes #102

### CODE REVIEW

**Comment by MarkGhebrial** [comment]
How do I fix the build error?

**Comment by MarkGhebrial** [comment]
I did not mean to close this PR, gimme a min...

File: photon-core/src/main/java/org/photonvision/vision/pipeline/OutputStreamPipeline.java [hunk 1]
```diff
@@ -126,6 +119,13 @@ public CVPipelineResult process(
             pipeProfileNanos[8] = 0;
         }
 
+        // Draw 2D contours on input and output
+        var draw2dTargetsOnInput = draw2dTargetsPipe.run(Pair.of(inMat, targetsToDraw));
+        sumPipeNanosElapsed += pipeProfileNanos[5] = draw2dTargetsOnInput.nanosElapsed;
```
Comment (Bankst) [inline photon-core/src/main/java/org/photonvision/vision/pipeline/OutputStreamPipeline.java:124]: this will technically break pipeline profiling, but as it was already broken it doesn't matter

**Review by Bankst — APPROVED** [review]
