### PR TITLE
Fix bug with saving general settings not using tempSettingsStruct and using store values instead

### LINKED ISSUE #1129: When changing hostname, the previous hostname is set instead
After fully rebooting the Pi with hostname set to photonvision-2: boot logs show was set to photonvision-2 at boot
After changing in web ui to photonvision-3: logs show `Jan 08 01:23:41 photonvision-2 java[728]: [2024-01-08 01:23:41] [General - NetworkManager] [INFO] Set hostname to photonvision-2`
After changing in web ui to photonvision-4: logs show `Jan 08 01:23:41 photonvision-2 java[728]: [2024-01-08 01:23:41] [General - NetworkManager] [INFO] Set hostname to photonvision-3`
After changing in web ui to photonvision-2: logs show `Jan 08 01:23:41 photonvision-2 java[728]: [2024-01-08 01:23:41] [General - NetworkManager] [INFO] Set hostname to photonvision-4`

### PR DESCRIPTION
**Pull request by srimanachanta**
residual from #1075 
closes #1129

### CODE REVIEW

File: photon-core/src/main/java/org/photonvision/common/configuration/NetworkConfig.java [hunk 1]
```diff
@@ -74,18 +74,18 @@ public NetworkConfig(
             @JsonProperty("runNTServer") boolean runNTServer,
             @JsonProperty("shouldManage") boolean shouldManage,
             @JsonProperty("shouldPublishProto") boolean shouldPublishProto,
-            @JsonProperty("networkManagerIface") String networkManagerIface,
+            @JsonProperty("networkManagerInterface") String networkManagerInterface,
             @JsonProperty("setStaticCommand") String setStaticCommand,
-            @JsonProperty("setDHCPcommand") String setDHCPcommand) {
+            @JsonProperty("setDHCPCommand") String setDHCPCommand) {
```
Comment (mcm001) [inline photon-core/src/main/java/org/photonvision/common/configuration/NetworkConfig.java:79]: Why chance these? It'll brick people's network configs if they try upgrading, potentially quietly.

Comment (srimanachanta) [reply photon-core/src/main/java/org/photonvision/common/configuration/NetworkConfig.java:79]: fair enough, undo, just weird naming imo.

**Review by mcm001 — APPROVED** [review]
