### PR TITLE
Fix OSHI spamming failures to console on Windows

### LINKED ISSUE #2280: OSHI spams failures to console on Windows
IS:

On Windows 11 + Ryzen 7700x, running via `./gradlew run` generates these extra logs to stdout that are not captured in our log files:

```
[2026-01-06 20:54:14] [NetworkTables - NetworkTablesManager] [DEBUG] Starting NT Client with hostname: DESKTOP-PNNHDMI
[2026-01-06 20:54:14] [NetworkTables - NetworkTablesManager] [INFO] NT: INFO 20: starting network client (NetworkClient.cpp:46)
[pool-1-thread-2] WARN oshi.hardware.platform.windows.WindowsSensors - Reflect exception: io.github.pandalxb.jlibrehardwaremonitor.config.ComputerConfig
[pool-1-thread-2] WARN oshi.util.platform.windows.WmiQueryHandler - COM exception querying MSAcpi_ThermalZoneTemperature, which might not be on your system. Will not attempt to query it again. Error was -2147217396: Failed to enumerate results.
[pool-1-thread-2] WARN oshi.hardware.platform.windows.WindowsSensors - Reflect exception: io.github.pandalxb.jlibrehardwaremonitor.config.ComputerConfig
[pool-1-thread-2] WARN oshi.util.platform.windows.WmiQueryHandler - COM exception querying MSAcpi_ThermalZoneTemperature, which might not be on your system. Will not attempt to query it again. Error was -2147217396: Failed to enumerate results.
[pool-1-thread-1] WARN oshi.hardware.platform.windows.WindowsSensors - Reflect exception: io.github.pandalxb.jlibrehardwaremonitor.config.ComputerConfig
[pool-1-thread-1] WARN oshi.util.platform.windows.WmiQueryHandler - COM exception querying MSAcpi_ThermalZoneTemperature, which might not be on your system. Will not attempt to query it again. Error was -2147217396: Failed to enumerate results.
[pool-1-thread-2] WARN oshi.hardware.platform.windows.WindowsSensors - Reflect exception: io.github.pandalxb.jlibrehardwaremonitor.config.ComputerConfig
[pool-1-thread-2] WARN oshi.util.platform.windows.WmiQueryHandler - COM exception querying MSAcpi_ThermalZoneTemperature, which might not be on your system. Will not attempt to query it again. Error was -2147217396: Failed to enumerate results.
[pool-1-thread-2] WARN oshi.hardware.platform.windows.WindowsSensors - Reflect exception: io.github.pandalxb.jlibrehardwaremonitor.config.ComputerConfig
[pool-1-thread-2] WARN oshi.util.platform.windows.WmiQueryHandler - COM exception querying MSAcpi_ThermalZoneTemperature, which might not be on your system. Will not attempt to query it again. Error was -2147217396: Failed to enumerate results.
[pool-1-thread-2] WARN oshi.hardware.platform.windows.WindowsSensors - Reflect exception: io.github.pandalxb.jlibrehardwaremonitor.config.ComputerConfig
[pool-1-thread-2] WARN oshi.util.platform.windows.WmiQueryHandler - COM exception querying MSAcpi_ThermalZoneTemperature, which might not be on your system. Will not attempt to query it again. Error was -2147217396: Failed to enumerate results.
[2026-01-06 20:54:20] [NetworkTables - NetworkTablesManager] [DEBUG] Starting NT Client with hostname: DESKTOP-PNNHDMI
[2026-01-06 20:54:20] [NetworkTables - NetworkTablesManager] [INFO] NT: INFO 20: starting network client (NetworkClient.cpp:46)
```

Output from administrator powershell:

```
PS C:\WINDOWS\system32> Get-WmiObject -Namespace "root/wmi" -Class MSAcpi_ThermalZoneTemperature
Get-WmiObject : Not supported
At line:1 char:1
+ Get-WmiObject -Namespace "root/wmi" -Class MSAcpi_ThermalZoneTemperat ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCommand

PS C:\WINDOWS\system32> Get-CimInstance -Namespace root/wmi -ClassName MSAcpi_ThermalZoneTemperature
Get-CimInstance : Not supported
At line:1 char:1
+ Get-CimInstance -Namespace root/wmi -ClassName MSAcpi_ThermalZoneTemp ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (root/wmi:MSAcpi_ThermalZoneTemperature:String) [Get-CimInstance], CimEx
   ception
    + FullyQualifiedErrorId : HRESULT 0x8004100c,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand

PS C:\WINDOWS\system32> Get-CimClass -Namespace root/wmi | Where-Object CimClassName -like "*Thermal*"


   NameSpace: ROOT/WMI

CimClassName                        CimClassMethods      CimClassProperties
------------                        ---------------      ------------------
KernelThermalPolicyChange           {}                   {SECURITY_DESCRIPTOR, TIME_CREATED, Active, CoolingMode...}
KernelThermalConstraintChange       {}                   {SECURITY_DESCRIPTOR, TIME_CREATED, Active, InstanceName...}
MSAcpi_ThermalZoneTemperature       {}                   {Active, ActiveTripPoint, ActiveTripPointCount, CriticalTri...


PS C:\WINDOWS\system32> Get-CimClass -Namespace root/wmi | Where-Object CimClassName -like "*Thermal*"


   NameSpace: ROOT/WMI

CimClassName                        CimClassMethods      CimClassProperties
------------                        ---------------      ------------------
KernelThermalPolicyChange           {}                   {SECURITY_DESCRIPTOR, TIME_CREATED, Active, CoolingMode...}
KernelThermalConstraintChange       {}                   {SECURITY_DESCRIPTOR, TIME_CREATED, Active, InstanceName...}
MSAcpi_ThermalZoneTemperature       {}                   {Active, ActiveTripPoint, ActiveTripPointCount, CriticalTripPoint...}


PS C:\WINDOWS\system32> Get-CimInstance -Namespace root/wmi -ClassName MSAcpi_ThermalZoneTemperature -ErrorAction Stop
Get-CimInstance : Not supported
At line:1 char:1
+ Get-CimInstance -Namespace root/wmi -ClassName MSAcpi_ThermalZoneTemp ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (root/wmi:MSAcpi_ThermalZoneTemperature:String) [Get-CimInstance], CimException
    + FullyQualifiedErrorId : HRESULT 0x8004100c,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand

PS C:\WINDOWS\system32>
```

S/B:

OSHI does not generate extra logs to stdout on failure

### PR DESCRIPTION
**Pull request by crschardt**
## Description

Monitoring CPU Temperature on Windows is challenging because most vendors don't publish this data to WMI. As a work-around, OSHI tries to use [LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor) via [jLibreHardwareMonitor](https://github.com/pandalxb/jLibreHardwareMonitor). If the temperature isn't found in WMI and jLibreHardwareMonitor isn't present, OSHI issues warnings every time `getCpuTemperature()` is called. This clogs the console with useless information when running on Windows and makes testing difficult.

We could include jLibreHardwareMonitor as a dependency for our Windows jar, but LibreHardwareMonitor installs Winring0.sys, which is a kernel level driver with an unfixed severe vulnerability. Windows defender flags Winring0 as a vulnuratble driver and blocks it from installing. Rather than messing with it, this PR prevents Windows systems from calling the `getCpuTemperature()` method in OSHI.

Fixes #2280

## Meta

Merge checklist:
- [x] Pull Request title is [short, imperative summary](https://cbea.ms/git-commit/) of proposed changes
- [x] The description documents the _what_ and _why_

### CODE REVIEW

**Review by mcm001 — DISMISSED** [review]

**Comment by Gold856** [comment]
Well, that's fun. The Javadoc is a _little_ inaccurate though, because jLibreHardwareMonitor isn't actually in the JAR. Can we clarify that? I just spent a bunch of time trying to figure out where the library was in the JAR...

**Review by crschardt — COMMENTED** [review]
It looks like the vulnerability is being addressed (https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/1857), but it hasn't made it into jLibreHarwareMonitor yet. We can revisit after the season if we think there is benefit to enabling temperature monitoring on Windows.

File: photon-core/src/main/java/org/photonvision/common/hardware/metrics/SystemMonitorWindows.java [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+    /**
+     * Monitoring CPU Temperature on Windows is challenging because most vendors don't publish this
+     * data to WMI. As a work-around, OSHI tries to use LibreHardwareMonitor via
+     * jLibreHardwareMonitor. If the temperature isn't found in WMI and jLibreHardwareMonitor isn't
+     * present, OSHI issues warnings every time getCpuTemperature() is called. This clogs the console
+     * with useless information when running on Windows and makes testing difficult.
+     *
+     * <p>We could include jLibreHardwareMonitor as a dependency for our Windows jar, but
+     * LibreHardwareMonitor installs Winring0.sys, which is a kernel-level driver with an unfixed
+     * severe vulnerability. Windows defender flags Winring0 as a vulnuratble driver and blocks it
```
Comment (Gold856) [inline photon-core/src/main/java/org/photonvision/common/hardware/metrics/SystemMonitorWindows.java]:
```suggestion
     * severe vulnerability. Windows defender flags Winring0 as a vulnerable driver and blocks it
```

**Comment by mcm001** [comment]
Windows doesn't need to report any metrics imo. If it does it's a cool bonus
